default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: data_development

test:
  <<: *default
  database: data_test

production:
  url: <%= ENV['DATABASE_URL'] %>
